services:
  app:
    hostname: hugo.niklas-stephan.de
    container_name: hugo.niklas-stephan.de
    build: .
    restart: unless-stopped
    volumes:
      - ./hugo.toml:/var/www/site/hugo.toml
      - ./content:/var/www/site/content
      - ./theme:/var/www/site/themes/nsde
    ports:
      - "1313:1313"
    environment:
      - STAGE=DEV
      - HUGO_THEME_GIT_URL=https://github.com/handtrixx/hugo-theme_niklas-stephan.de.git
      - HUGO_CONTENT_GIT_URL=https://github.com/handtrixx/content_niklas-stephan.de.git