services:
  app:
    hostname: hugo.niklas-stephan.de
    container_name: hugo.niklas-stephan.de
    build: .
    restart: unless-stopped
    volumes:
      - ./hugo:/var/www/site
    ports:
      - "1313:1313"
    env_file:
      - .env