services:
  nsde:
    image: niklas-stephan.de:latest
    hostname: nsde
    container_name: nsde
    restart: unless-stopped
    environment:
      - PRD_URL=https://niklas-stephan.de
      - QAS_URL=https://qas.niklas-stephan.de
      - DEV_URL=https://dev.niklas-stephan.de
      - HUGO_THEME_GIT_URL=https://github.com/handtrixx/hugo-theme_niklas-stephan.de.git
      - HUGO_CONTENT_GIT_URL=https://github.com/handtrixx/content_niklas-stephan.de.git
    volumes:
      - ../content_niklas-stephan.de:/var/www/dev/content
      - ../hugo-theme_niklas-stephan.de:/var/www/dev/themes/theme
    networks:
      - caddy
networks:
    caddy:
        external: true