baseURL = 'https://niklas-stephan.de'
title = 'niklas-stephan.de'
theme = 'theme'
languageCode = "de"                        # This is the default language code
defaultContentLanguage = "de"              # Set the default language
languageDirection = "ltr"
contentDir = 'content'
languageName = 'Deutsch'
ignoreLogs = ['warning-goldmark-raw-html']

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 20

[[menus.footer]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.footer]]
name = 'Blog'
pageRef = '/blog'
weight = 20

[[menus.footer]]
name = 'Datenschutz'
pageRef = '/privacy'
weight = 30

[[menus.footer]]
name = 'Impressum'
pageRef = '/imprint'
weight = 40

[[menus.footer]]
name = 'Suche'
pageRef = '/search'
weight = 50

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"

[outputs]
home = ["HTML", "JSON"]

[params]
# NAVIGATION
navbarbrand = 'iklas-stephan.de'
# COLORS
colorprimary = "#dc3545"
colorprimarylight = '#d70b0b'
colorsecondarylight = '#4b5257'
colorfooterbg = '#222020'
