theme = 'theme'
ignoreLogs = ['warning-goldmark-raw-html']
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true

[languages]
[languages.de]
languageName = "Deutsch"
weight = 1
contentDir = "content/de"
title = "niklas-stephan.de"
languageCode = "de"
languageDirection = "ltr"

# Language-specific menus for German
[[languages.de.menus.main]]
identifier = "home"
name = "Home"
url = "/de/"
weight = 10

[[languages.de.menus.main]]
identifier = "blog"
name = "Blog"
url = "/de/blog"
weight = 20

[[languages.de.menus.footer]]
identifier = "home"
name = "Home"
url = "/de/"
weight = 10

[[languages.de.menus.footer]]
identifier = "blog"
name = "Blog"
url = "/de/blog"
weight = 20

[[languages.de.menus.footer]]
identifier = "privacy"
name = "Datenschutz"
url = "/de/privacy"
weight = 30

[[languages.de.menus.footer]]
identifier = "imprint"
name = "Impressum"
url = "/de/imprint"
weight = 40

[[languages.de.menus.footer]]
identifier = "search"
name = "Suche"
url = "/de/search"
weight = 50


[languages.en]
languageName = "English"
weight = 2
contentDir = "content/de"
title = "niklas-stephan.de"
languageCode = "en"
languageDirection = "ltr"

# Language-specific menus for English
[[languages.en.menus.main]]
identifier = "home"
name = "Home"
url = "/en/"
weight = 10

[[languages.en.menus.main]]
identifier = "blog"
name = "Blog"
url = "/en/blog"
weight = 20

[[languages.en.menus.footer]]
identifier = "home"
name = "Home"
url = "/en/"
weight = 10

[[languages.en.menus.footer]]
identifier = "blog"
name = "Blog"
url = "/en/blog"
weight = 20

[[languages.en.menus.footer]]
identifier = "privacy"
name = "Privacy Policy"
url = "/en/privacy"
weight = 30

[[languages.en.menus.footer]]
identifier = "imprint"
name = "Imprint"
url = "/en/imprint"
weight = 40

[[languages.en.menus.footer]]
identifier = "search"
name = "Search"
url = "/en/search"
weight = 50

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
endLevel = 2
ordered = false
startLevel = 2
[markup.highlight]
noClasses = true
style = "github-dark"
lineNos = true
lineNumbersInTable = false

[module]
[module.hugoVersion]
extended = false
min = "0.115.0"
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"

[outputs]
home = ["HTML", "JSON"]

[build]
[build.buildStats]
enable = true

[params]
navbarbrand = 'iklas-stephan.de'
colorprimary = "#dc3545"
colorprimarylight = '#d70b0b'
colorsecondarylight = '#4b5257'
colorfooterbg = '#222020'

[params.giscus]
repo = "handtrixx/content_niklas-stephan.de"
repoID = "R_kgDOOFkuRg"
category = "Announcements"
categoryID = "DIC_kwDOOFkuRs4CoSNu"
mapping = "pathname"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "top"
lang = "de"
loading = "lazy"